name: Publish Package to NPM

on:
  workflow_dispatch:
    

jobs:
  Pack-And-Publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/publish
      with:
        registry-url: https://registry.npmjs.org/
        node-auth-token: ${{ secrets.NPM_REGISTRY_ACCESS_TOKEN }}
    