name: Publish to GitHub Packages

on:
  workflow_dispatch:
    

jobs:
  Pack-And-Publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/publish
      with:
        registry-url: https://npm.pkg.github.com
        node-auth-token: ${{ secrets.GITHUB_TOKEN }}
    