name: Publish to GitHub Packages

on:
  workflow_dispatch:
    

jobs:
  Pack-And-Publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/build
      name: Build and Compile
      with:
        registry-url: https://npm.pkg.github.com/
    - run: name=$(npm get name)
    - run: echo $name
    - run: npm publish
      name: Publish to GitHub Packages
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    