name: Publish Package to NPM

on:
  release:
    types: [published]
  workflow_dispatch:
    

jobs:
  Pack-And-Publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/build
      name: Build and Compile
      with:
        registry-url: https://registry.npmjs.org/
    - run: npm publish
      name: Publish to NPM
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY_ACCESS_TOKEN }}
    