name: Publish to GitHub Packages

on:
  workflow_dispatch:
    

jobs:
  Pack-And-Publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/build
      name: Build and Compile
      with:
        registry-url: https://npm.pkg.github.com/
    - run: name=$(npm pkg get name | sed -e 's/^"//' -e 's/"$//')
      name: Get Package Name
    - run: newname="@${{ github.repository_owner }}/$name"
      name: Set New Package Name
    - run: echo $newname
      name: Echo New Package Name
    - run: npm publish
      name: Publish to GitHub Packages
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    