name: Create Package and Upload Package

on:
  workflow_dispatch:
    

jobs:
  Pack-And-Upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: "Check out code"

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Install
      shell: bash
      run: npm install

    - name: Compile
      shell: bash
      run: npm run compile

    - name: Pack and Keep Filename
      run: filename=$(npm pack)
    
    - name: Set Filename
      run: echo "filename=$filename" >> $GITHUB_OUTPUT
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        path: ${{ steps.set-filename.outputs.filename }}
        name: package
